---
openapi: 3.0.1
info:
  title: springboot-oidc API
  version: v0
servers:
- url: http://192.168.29.118:8082
  description: Generated server url
paths:
  "/sample/message":
    get:
      tags:
        - Sample Controller
      operationId: getMessage
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
components:
  schemas:
    BaseResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: SecurityScheme(Bearer)
      bearerFormat: JWT
    openId:
      type: openIdConnect
      openIdConnectUrl: http://172.18.192.201:8080/realms/universe/.well-known/openid-configuration
      description: SecurityScheme(OpenIDConnect)
security:
  - bearerAuth: []
  - openId: []
